apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tu-usuario/webserver-helm-chart.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
